### ISSUE TITLE
How Can I initialize pool using PDA account?

### ISSUE THREAD

**Issue by magj2006** [raydium-io/raydium-cp-swap#10]
Hey, How Can I initialize pool using PDA account?  

PDA account is a System account, but creator is required Signer account.

**Comment by RainRaydium** [comment]
> Hey, How Can I initialize pool using PDA account?
> 
> PDA account is a System account, but creator is required Signer account.

You can refer to this link: https://solana.stackexchange.com/questions/6528/can-we-use-pda-as-signer-and-payer-to-create-an-account-in-any-solana-program

**Comment by obstoody** [comment]
@RainRaydium 
Regarding the reference link you provided, one answer said it is not possible, while another answer said it's possible.
From my perspective, utilizing the PDA as the payer seems viable.
Could you please confirm this?
