### ISSUE TITLE
bug: 3 Test fail

### ISSUE THREAD

**Issue by PhatStraw** [raydium-io/raydium-cp-swap#14]
![Screenshot 2024-06-21 at 9 08 10 PM](https://github.com/raydium-io/raydium-cp-swap/assets/49126398/6ebee814-8384-4eb3-98de-cfd1cd0d1da0)

Cloned repo, ran anchor test and 3 test fail

**Comment by Henry-E** [comment]
Came here to post this as well. The repo doesn't run out of the box, those three tests fail.

**Comment by RainRaydium** [comment]
It's Ok now.
