### ISSUE TITLE
How to fix "Stack offset of 4848 exceeded max offset" after building

### ISSUE THREAD

**Issue by benhaben** [raydium-io/raydium-cp-swap#18]
Error: Function _ZN161_$LT$raydium_cp_swap..instructions..initialize..Initialize$u20$as$u20$anchor_lang..Accounts$LT$raydium_cp_swap..instructions..initialize..InitializeBumps$GT$$GT$12try_accounts17h1a5660f3939c4019E Stack offset of 4848 exceeded max offset of 4096 by 752 bytes, please minimize large stack variables

**Comment by TwentyOne37** [comment]
Same issue here.

**Comment by TwentyOne37** [comment]
If you update dependecy for this commit:

`raydium-cp-swap = { git = "https://github.com/raydium-io/raydium-cp-swap", rev = "2562fa8d171ecbdbcaff8503d00fa16ca3c74d26", features = [...] }`

Anchor should compile the code, however it will be problematic to use on-chain. Probably adding `observation_state` to `Initialize` had overflowed stack size.

https://github.com/raydium-io/raydium-cp-swap/commit/2562fa8d171ecbdbcaff8503d00fa16ca3c74d26

**Comment by me-imfhd** [comment]
```

use anchor_spl::associated_token::{create as create_ata, Create as CreateAta};
...
/// creator lp token account
    #[account(
        // init,
        associated_token::mint = lp_mint,
        associated_token::authority = creator,
        // payer = creator,
        token::token_program = token_program,
    )]
    pub creator_lp_token: Box<InterfaceAccount<'info, TokenAccount>>,
 ...
 
create_ata(CpiContext::new(
        ctx.accounts.token_program.to_account_info(),
        CreateAta {
            associated_token: ctx.accounts.creator_lp_token.to_account_info(),
            authority: ctx.accounts.creator.to_account_info(),
            mint: ctx.accounts.lp_mint.to_account_info(),
            payer: ctx.accounts.creator.to_account_info(),
            system_program: ctx.accounts.system_program.to_account_info(),
            token_program: ctx.accounts.token_program.to_account_info(),
        },
    ))?;
```

Initializing the lp_token_account inside the program instead of using init fixes this

**Comment by me-imfhd** [comment]
It's not a problem when you actually invoke the instruction when running test.

**Comment by RainRaydium** [comment]
> Error: Function _ZN161_$LT$raydium_cp_swap..instructions..initialize..Initialize$u20$as$u20$anchor_lang..Accounts$LT$raydium_cp_swap..instructions..initialize..InitializeBumps$GT$$GT$12try_accounts17h1a5660f3939c4019E Stack offset of 4848 exceeded max offset of 4096 by 752 bytes, please minimize large stack variables

Currently, we recommend depend on versions anchor 0.29 and below solana 1.18. There are optimizations for related issues in anchor 0.31 [https://github.com/coral-xyz/anchor/pull/2939](url)
After anchor 0.31 is officially released, we will upgrade the dependencies. Thank you.
